### ISSUE TITLE
Toggleable context window

### ISSUE THREAD

**Issue by meain** [zbelial/treesitter-context.el#10]
First of all, thanks a lot for the package. I've been meaning to writing something similar for some time.

It might be useful to have a function that can toggle the context window on/off. Something like below:

``` emacs-lisp
(lambda ()
  (interactive)
  (if meain/treesitter-context-shown
      (progn
        (treesitter-context--hide-frame)
        (setq meain/treesitter-context-shown nil))
    (progn
      (treesitter-context--refresh-context)
      (treesitter-context--show-context)
      (setq meain/treesitter-context-shown t))))
```

Just thought I would suggest here, but feel free to close the issue if you don't feel like it would be useful.

**Comment by zbelial** [comment]
Hi, thanks. 
You want to temporarily hide the context window, right?  IIUC, if you toggle context window off with your code, the window will show again after `treesitter-context-idle-time`.   Can you describe your expectation in more detail? 

Actually, pressing C-g will hide the context window, but because `treesitter-context--refresh-when-idle` is in `post-command-hook`, and C-g is a command, so after pressing C-g, the context will show again.  **But this isn't what I expect too,  there is a bug here** .  I'll think more about how to temporarily hide the context window.

**Comment by meain** [comment]
In the scenario I mentioned, `treesitter-context-mode` is not enabled and there are no timers running. You only display it when you need it with a keybinding and hide it with a timer or with the same keybinding.

```emacs-lisp
(global-set-key (kbd "M-r")
                (lambda ()
                  (interactive)
                  (if meain/treesitter-context-shown
                      (progn
                        (treesitter-context--hide-frame)
                        (setq meain/treesitter-context-shown nil))
                    (progn
                      (treesitter-context--refresh-context)
                      (treesitter-context--show-context)
                      (setq meain/treesitter-context-shown t)))))
```

**Comment by zbelial** [comment]
I see. Thanks for explaining. 
This really is useful in some cases, I think I'll add a command then.

**Comment by zbelial** [comment]
Hi @meain 
I just added a new command `treesitter-context-toggle-show` in file `treesitter-context-utils.el`. 
You should require `treesitter-context-utils` first to use this command.  

Is this command what you wanted?

**Comment by meain** [comment]
Yup, exactly what I was looking for. Thank you!
